# Generated by Django 6.0.2 on 2026-02-14 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_devicetoken'),
        ('regions', '0002_region_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_safe',
            field=models.BooleanField(default=False, help_text='Whether user has marked themselves as safe'),
        ),
        migrations.AddField(
            model_name='user',
            name='location_region',
            field=models.ForeignKey(blank=True, help_text="User's current location region", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safe_users', to='regions.region'),
        ),
        migrations.AddField(
            model_name='user',
            name='safe_status_updated_at',
            field=models.DateTimeField(blank=True, help_text='When user last updated their safety status', null=True),
        ),
    ]
