# Generated by Codex on 2026-05-29

from django.db import migrations, models


def fill_unique_phone_numbers(apps, schema_editor):
    User = apps.get_model('accounts', 'User')

    seen = set()
    for user in User.objects.order_by('id'):
        phone = (user.phone_number or '').strip()
        if not phone:
            phone = f'+92 000-{int(user.id):07d}'

        if phone in seen or User.objects.exclude(id=user.id).filter(phone_number=phone).exists():
            phone = f'{phone}-{user.id}'

        user.phone_number = phone[:20]
        user.save(update_fields=['phone_number'])
        seen.add(user.phone_number)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_logged_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text="User's unique contact phone number", max_length=20, null=True),
        ),
        migrations.RunPython(fill_unique_phone_numbers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text="User's unique contact phone number", max_length=20, unique=True),
        ),
    ]
