# Generated by Django 5.0.1 on 2026-05-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dark_mode',
            field=models.BooleanField(default=False, help_text='Whether the user has dark mode enabled'),
        ),
    ]
