# Generated by Django 5.0.1 on 2026-05-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_authorityprofile_residentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetoken',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latest known device latitude for radius-based alert targeting', null=True),
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, help_text='When this device location was last updated', null=True),
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Latest known device longitude for radius-based alert targeting', null=True),
        ),
    ]
