# Generated by Codex on 2026-06-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_devicetoken_latitude_devicetoken_location_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='push_notifications_enabled',
            field=models.BooleanField(
                default=True,
                help_text='Whether the user wants to receive push notifications',
            ),
        ),
    ]
