# Generated by Django 5.0.1 on 2026-02-04 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("regions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="LOW",
                        help_text="Alert severity level",
                        max_length=10,
                    ),
                ),
                (
                    "message",
                    models.TextField(help_text="Detailed alert message or warning"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this alert is currently active"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the alert was created"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the alert was resolved/deactivated",
                        null=True,
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        help_text="Region this alert is issued for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="regions.region",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alert",
                "verbose_name_plural": "Alerts",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="alerts_aler_timesta_0459bf_idx"
                    ),
                    models.Index(
                        fields=["is_active", "-timestamp"],
                        name="alerts_aler_is_acti_20ddb2_idx",
                    ),
                ],
            },
        ),
    ]
