# Generated by Django 5.0.1 on 2026-02-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='affected_population',
            field=models.IntegerField(default=0, help_text='Estimated number of people affected'),
        ),
    ]
