# Generated by Django 5.0.1 on 2026-02-04 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("regions", "0002_region_last_updated"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IncidentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the incident"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional photo evidence",
                        null=True,
                        upload_to="incident_images/",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the report was submitted"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether authorities have verified this report",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        help_text="Region where incident occurred",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incident_reports",
                        to="regions.region",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who reported the incident",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incident_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Incident Report",
                "verbose_name_plural": "Incident Reports",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SafetyStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_safe",
                    models.BooleanField(
                        default=True,
                        help_text="Whether user has marked themselves as safe",
                    ),
                ),
                (
                    "last_marked_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last time user updated their status"
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        help_text="Region where user is located",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safety_statuses",
                        to="regions.region",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User marking their safety status",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safety_statuses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Safety Status",
                "verbose_name_plural": "Safety Statuses",
                "ordering": ["-last_marked_at"],
                "unique_together": {("user", "region")},
            },
        ),
    ]
