# Generated by Django 5.0.1 on 2026-05-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetystatus',
            name='area_name',
            field=models.CharField(blank=True, help_text='Human-readable area name for the check-in location', max_length=255),
        ),
        migrations.AddField(
            model_name='safetystatus',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude where the user marked themselves safe', null=True),
        ),
        migrations.AddField(
            model_name='safetystatus',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude where the user marked themselves safe', null=True),
        ),
    ]
