# Generated by Codex on 2026-05-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_sosrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='area_name',
            field=models.CharField(blank=True, help_text='Human-readable incident location', max_length=255),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude where the incident was reported', null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude where the incident was reported', null=True),
        ),
    ]
