# Generated by Codex on 2026-05-30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0004_region_danger_radius_km_region_is_critical_zone_and_more'),
        ('reports', '0005_sosrequest_start_time_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='region',
            field=models.ForeignKey(
                blank=True,
                help_text='Region where incident occurred',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='incident_reports',
                to='regions.region',
            ),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='report_radius_km',
            field=models.FloatField(
                default=50.0,
                help_text='Approximate radius covered by this report',
            ),
        ),
    ]
