# Generated by Django 5.0.1 on 2026-06-11 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_incidentreport_optional_region_radius'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='hazard_level',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], help_text='Authority-assigned level, available only for approved reports', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='review_status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_incident_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='report_radius_km',
            field=models.FloatField(default=20.0, help_text='Approximate radius covered by this report'),
        ),
    ]
