# Generated by Django 5.0.1 on 2026-06-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_incidentreport_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='report_radius_km',
            field=models.FloatField(default=10.0, help_text='Approximate radius covered by this report'),
        ),
    ]
