# Generated by Django 5.0.1 on 2026-06-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_incidentreport_report_radius_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='review_notes',
            field=models.TextField(blank=True, default='', help_text='Optional notes from the authority during review'),
        ),
    ]
