# Generated by Django 5.0.1 on 2026-02-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the region (e.g., 'Murree Hills')",
                        max_length=200,
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        help_text="District name (e.g., 'Rawalpindi')", max_length=200
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(help_text="Geographical latitude coordinate"),
                ),
                (
                    "longitude",
                    models.FloatField(help_text="Geographical longitude coordinate"),
                ),
                (
                    "current_risk_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Current landslide risk score (0.0 to 1.0)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Region",
                "verbose_name_plural": "Regions",
                "ordering": ["-current_risk_score", "name"],
                "unique_together": {("name", "district")},
            },
        ),
    ]
