# Generated by Django 5.0.1 on 2026-02-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Last time weather data was fetched for this region",
            ),
        ),
    ]
