# Generated by Django 5.0.1 on 2026-05-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_region_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerrainSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude_key', models.DecimalField(decimal_places=4, max_digits=8)),
                ('longitude_key', models.DecimalField(decimal_places=4, max_digits=9)),
                ('requested_latitude', models.FloatField()),
                ('requested_longitude', models.FloatField()),
                ('elevation_m', models.FloatField(blank=True, null=True)),
                ('slope_degrees', models.FloatField(blank=True, null=True)),
                ('elevation_code', models.IntegerField(default=2)),
                ('slope_code', models.IntegerField(default=2)),
                ('soil_type', models.CharField(blank=True, default='', max_length=80)),
                ('soil_code', models.IntegerField(default=2)),
                ('clay_percent', models.FloatField(blank=True, null=True)),
                ('sand_percent', models.FloatField(blank=True, null=True)),
                ('silt_percent', models.FloatField(blank=True, null=True)),
                ('lithology_type', models.CharField(blank=True, default='unknown', max_length=80)),
                ('lithology_code', models.IntegerField(default=2)),
                ('ndvi_code', models.IntegerField(default=2)),
                ('ndwi_code', models.IntegerField(default=2)),
                ('elevation_source', models.CharField(blank=True, default='', max_length=80)),
                ('soil_source', models.CharField(blank=True, default='', max_length=80)),
                ('data_quality', models.CharField(default='partial', max_length=40)),
                ('fetch_errors', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Terrain Sample',
                'verbose_name_plural': 'Terrain Samples',
                'indexes': [models.Index(fields=['latitude_key', 'longitude_key'], name='regions_ter_latitud_32faed_idx')],
                'unique_together': {('latitude_key', 'longitude_key')},
            },
        ),
    ]
