# Generated by Django 5.0.1 on 2026-05-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0003_terrainsample'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='danger_radius_km',
            field=models.FloatField(default=5.0, help_text='Distance from region center considered inside the hazard zone'),
        ),
        migrations.AddField(
            model_name='region',
            name='is_critical_zone',
            field=models.BooleanField(default=True, help_text='Whether this region represents a monitored landslide hazard zone'),
        ),
        migrations.AddField(
            model_name='region',
            name='warning_radius_km',
            field=models.FloatField(default=15.0, help_text='Distance from region center considered near the hazard zone'),
        ),
    ]
