# Generated by Django 5.0.1 on 2026-06-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0004_region_danger_radius_km_region_is_critical_zone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='danger_radius_km',
            field=models.FloatField(default=10.0, help_text='Distance from region center considered inside the hazard zone'),
        ),
        migrations.AlterField(
            model_name='region',
            name='warning_radius_km',
            field=models.FloatField(default=10.0, help_text='Distance from region center considered near the hazard zone'),
        ),
    ]
