# Generated by Codex on 2026-05-29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_emergency_contacts(apps, schema_editor):
    EmergencyContact = apps.get_model('safety', 'EmergencyContact')
    contacts = [
        ('Rescue 1122', '1122', 'Emergency Rescue Services', 'ambulance', 1),
        ('Police', '15', 'Police Emergency', 'shield', 2),
        ('Fire Brigade', '16', 'Fire Emergency', 'flame', 3),
    ]
    for name, number, description, icon, sort_order in contacts:
        EmergencyContact.objects.get_or_create(
            number=number,
            defaults={
                'name': name,
                'description': description,
                'icon': icon,
                'sort_order': sort_order,
                'is_active': True,
            },
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('number', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=180)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Emergency Contact',
                'verbose_name_plural': 'Emergency Contacts',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SavedSafetyTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_id', models.CharField(max_length=80)),
                ('tip_title', models.CharField(max_length=180)),
                ('tip_description', models.TextField()),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_safety_tips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Safety Tip',
                'verbose_name_plural': 'Saved Safety Tips',
                'ordering': ['-saved_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='savedsafetytip',
            constraint=models.UniqueConstraint(fields=('user', 'tip_id'), name='unique_saved_safety_tip_per_user'),
        ),
        migrations.RunPython(seed_emergency_contacts, migrations.RunPython.noop),
    ]
